spring:
  datasource:
    driver-class-name: org.hibernate.dialect.MySQL8Dialect
    username: developer
    url: jdbc:mysql://localhost:3306/fornecedor
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
