spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: developer
    url: jdbc:mysql://localhost:3306/fornecedor
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
